name: Python Safety Check
on:
    push:
        branches:
        - main
env:
  DEP_PATH: comp7940-lab/requirements.txt
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Python Safety Check
        uses: aufdenpunkt/python-safety-check@v1.0.5
         with:
    safety_args:'-i 1234' 
    scan_requirements_file_only: false # optional, default is false






