name: Python Safety Check
on:
    push:
        branches:
        - main
env:
  DEP_PATH: comp7940-lab/requirements.txt
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
       - name: Security vulnerabilities scan
         uses: aufdenpunkt/python-safety-check@master
         with:
          scan_requirements_file_only: 'true'





